from typing import Protocol
from shared.domain import SessionID


class AgentClientPort(Protocol):
    async def demarrer_session(self, session_id: SessionID) -> None: ...
    async def traiter_reponse(self, session_id: SessionID, texte_reponse: str) -> tuple[str, bool]: ...
    async def terminer_session(self, session_id: SessionID) -> None: ...