from typing import Protocol
from domain.value_objects.session_id import SessionId


class AgentClientPort(Protocol):
    async def demarrer_session(self, session_id: SessionId) -> None: ...
    async def traiter_reponse(self, session_id: SessionId, texte_reponse: str) -> tuple[str, bool]: ...
    async def terminer_session(self, session_id: SessionId) -> None: ...