from typing import Awaitable, Callable, Protocol
from shared.domain import SessionID, AudioChunk, TranscriptionResult

ResultCallback = Callable[[TranscriptionResult], Awaitable[None]]


class ASRClientPort(Protocol):
    async def demarrer_session(self, session_id: SessionID, language: str) -> None: ...
    async def envoyer_chunk(self, session_id: SessionID, chunk: AudioChunk) -> None: ...
    async def signaler_fin_de_tour(self, session_id: SessionID) -> None: ...
    async def terminer_session(self, session_id: SessionID) -> None: ...
    def souscrire_resultats(self, session_id: SessionID, callback: ResultCallback) -> None: ...
    def est_fin_de_parole_detectee(self, session_id: SessionID) -> bool: ...