from typing import Protocol
from shared.domain import SessionID


class SessionClientPort(Protocol):
    async def valider_session(self, session_id: SessionID) -> bool: ...
    async def notifier_coupure(self, session_id: SessionID, raison: str) -> None: ...
    async def notifier_reconnexion(self, session_id: SessionID) -> None: ...