from typing import AsyncIterator, Protocol
from shared.domain import SessionID, AudioChunk


class TTSClientPort(Protocol):
    async def demarrer_session(self, session_id: SessionID, voice: str) -> None: ...
    def synthetiser_stream(self, session_id: SessionID, texte: str) -> AsyncIterator[AudioChunk]: ...
    async def terminer_session(self, session_id: SessionID) -> None: ...